### ISSUE TITLE
Image should include everything that is needed to build

### ISSUE THREAD

**Issue by Hades32** [docker-swift/docker-swift#4]
I like to use docker as by build tool, so I don't have to install anything. It also makes it super easy for other people to build your stuff.

Also, I'm NOT a fan of building inside the same container, that you will ship. Build tools are just too large and are a potential surface.

e.g. my current build file now looks like this:
```bash
#!/bin/sh

dir=`readlink -f $(dirname $0)`

docker run -it --rm --name swiftc-test1 -v="$dir":/app -w=/app swiftlang/swift swift build
```
This will unfortunately fail typically, because Git is needed to download dependencies.

I'd therefore suggest that you include (or provide an alternative image) that includes Git (and whatever else is typically needed for a build).

**Comment by joein3d** [comment]
Makes sense- I was installing git on top of this image but it should be included since Swift's package manager uses it.
